minecraft-server:
  ports:
    - "25565:25565"
  
  image: wolfrazu/ftb-omnia:latest

  container_name: ftb_omnia

  tty: true
  stdin_open: true
  restart: unless-stopped
  volumes:
    - /opt/wolfware/mounts/FTBOmnia:/usr/src/ftbomnia
